## ==================================================================================================
## PRE
## ==================================================================================================

#Ityneri PRE
pre_ityneri_base_url="https://pre-autocorb.actiosae.com/"
pre_ityneri_api_key="AIzaSyCsGlKAPUs8GM7iPaF-YJv5gosE9U9C_bY"
pre_ityneri_places_api_key="AIzaSyCVwN9Lsi7kzCDVS9RfanaU23hG1oi8VP0"
pre_ityneri_maps_api_key=AIzaSyCu2DVpkh_HOobHlTDlnGfCWVnuM-JvY_0
pre_ityneri_alerts_url="https://pre-autocorb.actiosae.com/api/alerts"
pre_ityneri_allowCustomFavName=false
pre_ityneri_showBannerImage=true
pre_ityneri_useSavedConnectionsOfFavoriteStops=false
pre_ityneri_suggestionMoreScreen=false
pre_ityneri_language_ca=false
pre_ityneri_label_web=true
pre_ityneri_on_demand=false
pre_ityneri_multi_feed=false
pre_ityneri_suggestion_optionals=false
pre_ityneri_list_multi_feeds=false
pre_ityneri_firebase_crashlytics=true
pre_ityneri_firebase_analytics=false

## ==================================================================================================
## PR0
## ==================================================================================================

#Ityneri PRO
ityneri_feed_id="autocorb"
pro_ityneri_base_url="https://autocorb.actiosae.com/"
pro_ityneri_api_key="AIzaSyBdyIP1A24iAfXYY82GTQpH9anEHTYgl6Q"
pro_ityneri_places_api_key="AIzaSyCVwN9Lsi7kzCDVS9RfanaU23hG1oi8VP0"
pro_ityneri_maps_api_key=AIzaSyCu2DVpkh_HOobHlTDlnGfCWVnuM-JvY_0
pro_ityneri_alerts_url="https://autocorb.actiosae.com/api/alerts"
ityneri_lat_reference=41.4167
ityneri_lng_reference=1.9333
ityneri_zoom_reference=14.5f
ityneri_url_web="https://geoactio.com/soluciones/actiosae/"
pro_ityneri_allowCustomFavName=false
pro_ityneri_showBannerImage=true
pro_ityneri_useSavedConnectionsOfFavoriteStops=false
pro_ityneri_suggestionMoreScreen=false
ityneri_timetableMoreScreen=false
ityneri_language_ca=false
ityneri_label_web=true
ityneri_on_demand=false
ityneri_multi_feed=false
ityneri_suggestion_optionals=false
ityneri_list_multi_feeds=false
ityneri_firebase_crashlytics=true
ityneri_firebase_analytics=false


#Masats PRO
masats_feed_id="masats"
pro_masats_base_url="https://masats.actiosae.com/"
pro_masats_api_key="AIzaSyBKeL_8s1L0Cuqbzc0Npv2gegAsoG_yZpM"
pro_masats_places_api_key="AIzaSyCiFN4vx7fzC573JHJJPr-pmy4-EXMkb7M"
pro_masats_maps_api_key=AIzaSyCogRkAXd2R93Sb4cHeDLreapF_PBrHqw4
pro_masats_alerts_url="https://api.gruptg.com/arthorarios.aspx?MASATS"
masats_lat_reference=41.584032
masats_lng_reference=1.615791
masats_zoom_reference=14.5f
masats_url_web="https://www.gruptg.com/"
masats_allowCustomFavName=false
masats_showBannerImage=false
masats_useSavedConnectionsOfFavoriteStops=false
masats_suggestionMoreScreen=false
masats_timetableMoreScreen=false
masats_language_ca=true
masats_label_web=true
masats_on_demand=false
masats_multi_feed=false
masats_suggestion_optionals=false
masats_list_multi_feeds=false
masats_firebase_crashlytics=true
masats_firebase_analytics=false

#TGO
tgo_feed_id="tgo"
pro_tgo_base_url="https://tgo.actiosae.com/"
pro_tgo_api_key="AIzaSyBKeL_8s1L0Cuqbzc0Npv2gegAsoG_yZpM"
pro_tgo_places_api_key="AIzaSyB6KJCe2gx1yT9SeccdFk-4bWxE_mrglF4"
pro_tgo_maps_api_key=AIzaSyAu0ev8vTcLq2f9guHm882qmvjXln241Mg
pro_tgo_alerts_url="https://api.gruptg.com/arthorarios.aspx?TGO"
tgo_lat_reference=41.556864
tgo_lng_reference=2.006978
tgo_zoom_reference=11f
tgo_url_web="https://www.gruptg.com/"
tgo_allowCustomFavName=false
tgo_showBannerImage=false
tgo_useSavedConnectionsOfFavoriteStops=false
tgo_suggestionMoreScreen=false
tgo_timetableMoreScreen=false
tgo_language_ca=true
tgo_label_web=true
tgo_on_demand=false
tgo_multi_feed=false
tgo_suggestion_optionals=false
tgo_list_multi_feeds=false
tgo_firebase_crashlytics=true
tgo_firebase_analytics=false

//AUTOCORB
pro_autocorb_places_api_key="AIzaSyAOE44jl2UKtqzEn8A67au3zIvqtwRkrKQ"
pro_autocorb_maps_api_key=AIzaSyBIIARLc4goWClTbT8gOlavvC-q8euYNaw
autocorb_url_web="https://www.autocorb.com/"
pro_autocorb_allowCustomFavName=false
pro_autocorb_showBannerImage=false
pro_autocorb_useSavedConnectionsOfFavoriteStops=false
autocorb_suggestionMoreScreen=false
autocorb_timetableMoreScreen=false
autocorb_language_ca=false
autocorb_label_web=true
autocorb_on_demand=false
autocorb_multi_feed=false
autocorb_suggestion_optionals=false
autocorb_list_multi_feeds=false
autocorb_firebase_crashlytics=true
autocorb_firebase_analytics=false


//HILLSA
hillsa_feed_id="hillsa"
pro_hillsa_base_url="https://hillsa.actiosae.com/"
pro_hillsa_api_key="AIzaSyAFHVIwrRgqQorXc8Bih-dPOfAtEAoNFlM"
pro_hillsa_places_api_key="AIzaSyCuDI-xGS2eCfrY_vJYSGlnVD3KftwKIuk"
pro_hillsa_maps_api_key=AIzaSyDS3MoCQ_vaQ5EffbY7hT9XC-rzf3nrJ4U
hillsa_lat_reference=41.472885
hillsa_lng_reference=1.858862
hillsa_zoom_reference=12.5f
hillsa_url_web="https://hillsabus.com/"
hillsa_allowCustomFavName=false
hillsa_showBannerImage=false
hillsa_useSavedConnectionsOfFavoriteStops=false
hillsa_suggestionMoreScreen=false
hillsa_timetableMoreScreen=false
hillsa_language_ca=false
hillsa_label_web=true
hillsa_on_demand=false
hillsa_multi_feed=false
hillsa_suggestion_optionals=false
hillsa_list_multi_feeds=false
hillsa_firebase_crashlytics=true
hillsa_firebase_analytics=false

#HARO
haro_feed_id="haro"
pro_haro_base_url="https://jimenez.actiosae.com/"
pro_haro_api_key="AIzaSyDeVAltig7-4I8hhjqmEMFylXWbGVGMj94"
pro_haro_places_api_key="AIzaSyDeVAltig7-4I8hhjqmEMFylXWbGVGMj94"
pro_haro_maps_api_key=AIzaSyDeVAltig7-4I8hhjqmEMFylXWbGVGMj94
haro_lat_reference=42.572761
haro_lng_reference=-2.850361
haro_zoom_reference=14.5f
haro_url_web="https://jimenezmovilidad.es/wp-content/uploads/2024/04/Haro-vertical-2.1.pdf/"
haro_allowCustomFavName=false
haro_showBannerImage=true
haro_useSavedConnectionsOfFavoriteStops=false
haro_suggestionMoreScreen=false
haro_timetableMoreScreen=false
haro_language_ca=false
haro_label_web=false
haro_on_demand=false
haro_multi_feed=false
haro_suggestion_optionals=false
haro_list_multi_feeds=false
haro_firebase_crashlytics=true
haro_firebase_analytics=false

//ARROYO
arroyo_feed_id="arroyo"
pro_arroyo_base_url="https://arroyo.actiosae.com/"
pro_arroyo_api_key="AIzaSyAU1JU1KAwodMajPhSKBeTBDkTYNSWK8TE"
pro_arroyo_places_api_key="AIzaSyCThuiS8Y265a0SS_QZCmwEMDEF9Al4E5A"
pro_arroyo_maps_api_key=AIzaSyCThuiS8Y265a0SS_QZCmwEMDEF9Al4E5A
arroyo_lat_reference=41.612460
arroyo_lng_reference=-4.786581
arroyo_zoom_reference=14.5f
arroyo_url_web="https://www.aytoarroyo.es/"
arroyo_allowCustomFavName=false
arroyo_showBannerImage=false
arroyo_useSavedConnectionsOfFavoriteStops=true
arroyo_suggestionMoreScreen=true
arroyo_timetableMoreScreen=false
arroyo_language_ca=false
arroyo_label_web=true
arroyo_on_demand=false
arroyo_multi_feed=false
arroyo_suggestion_optionals=true
arroyo_list_multi_feeds=false
arroyo_firebase_crashlytics=true
arroyo_firebase_analytics=false

//SMIR
smir_feed_id="metropolitano"
pro_smir_base_url="https://smir.actiosae.com/"
pro_smir_api_key="AIzaSyBvAJvwgicaMwQBfNRftbAlqY2O4p7OAlU"
pro_smir_alerts_url="https://smir.actiosae.com/api/v2/config/alert/list"
pro_smir_maps_api_key=AIzaSyB-ND7qKiPK31r4qNlx2utqZd2CWI9q_v4
smir_lat_reference=42.3835713
smir_lng_reference=-2.804574
smir_zoom_reference=10.24f
smir_url_web="https://www.larioja.org/transportes/es"
smir_allowCustomFavName=true
smir_showBannerImage=false
smir_useSavedConnectionsOfFavoriteStops=true
smir_suggestionMoreScreen=false
smir_timetableMoreScreen=false
smir_language_ca=false
smir_label_web=true
smir_on_demand=true
smir_multi_feed=false
smir_suggestion_optionals=false
smir_show_bus_on_map=false
smir_feeds=metropolitano,interurbano,rural
smir_list_multi_feeds=true
smir_firebase_crashlytics=true
smir_firebase_analytics=true

#Aragon
aragon_feed_id="aragon"
pro_aragon_base_url="https://jimenez.actiosae.com"
pro_aragon_api_key="AIzaSyDeVAltig7-4I8hhjqmEMFylXWbGVGMj94"
pro_aragon_places_api_key="AIzaSyCThuiS8Y265a0SS_QZCmwEMDEF9Al4E5A"
pro_aragon_maps_api_key=AIzaSyDCwlr6jC2C9heaTSyLcvmj1M3PWw3te5Y
aragon_lat_reference=41.041915
aragon_lng_reference=-1.263308
aragon_zoom_reference=8.24f
aragon_url_web="https://zaragozateruel.jimenezmovilidad.es/"
aragon_allowCustomFavName=true
aragon_showBannerImage=true
aragon_useSavedConnectionsOfFavoriteStops=true
aragon_suggestionMoreScreen=false
aragon_timetableMoreScreen=false
aragon_language_ca=false
aragon_label_web=true
aragon_on_demand=true
aragon_multi_feed=false
aragon_suggestion_optionals=false
aragon_list_multi_feeds=false
aragon_firebase_crashlytics=true
aragon_firebase_analytics=false

//GETIN
#TODO: Esta instancia es multifeed, para versi�n beta se usa uno solo
getin_feed_id="23"
getin_base_url="https://getin.actiosae.com"
getin_api_key="AIzaSyCX_Iuh2q4QBjnTrXO95hFDvYBB6JPxqc4"
getin_maps_api_key=AIzaSyAU1JU1KAwodMajPhSKBeTBDkTYNSWK8TE
getin_lat_reference=42.324270
getin_lng_reference=-1.383228
getin_zoom_reference=8.62f
getin_url_web=""
getin_allowCustomFavName=true
getin_showBannerImage=false
getin_useSavedConnectionsOfFavoriteStops=true
getin_suggestionMoreScreen=false
getin_timetableMoreScreen=false
getin_language_ca=false
getin_label_web=false
getin_on_demand=false
getin_multi_feed=false
getin_suggestion_optionals=false
getin_list_multi_feeds=false
getin_firebase_crashlytics=true
getin_firebase_analytics=false

