//ARROYOPRE
pre_arroyo_base_url="https://autocorb-dev.actiosae.com/"
pre_arroyo_api_key="AIzaSyBQ7MA1Rr9IlDDbIOdiNa-jGP6WL_O5pPE"

//ARROYOPRO
pro_arroyo_base_url="https://arroyo.actiosae.com/"
pro_arroyo_api_key="AIzaSyAU1JU1KAwodMajPhSKBeTBDkTYNSWK8TE"

#MASATSPRE
pre_masats_base_url="https://autocorb-dev.actiosae.com/"
pre_masats_api_key="AIzaSyBQ7MA1Rr9IlDDbIOdiNa-jGP6WL_O5pPE"

#MASATSPRO
pro_masats_base_url="https://masats.actiosae.com/"
pro_masats_api_key="AIzaSyCYgq7lNrwpbt7QuYIcF65m23sc0KTDnRM"

#TGOPRE
pre_tgo_base_url="https://autocorb-dev.actiosae.com/"
pre_tgo_api_key="AIzaSyBQ7MA1Rr9IlDDbIOdiNa-jGP6WL_O5pPE"

#TGOPRO
pro_tgo_base_url="https://tgo.actiosae.com/"
pro_tgo_api_key="AIzaSyBKeL_8s1L0Cuqbzc0Npv2gegAsoG_yZpM"

//DEFAULT
empty_base_url=""
empty_api_key=""